version: "3.8"

services:
  ai-models:
    build:
      context: .
    volumes:
      - .:/app
    container_name: ai-models
    ports:
      - "8084:8000"
    env_file:
      - .env
    networks:
      - my-net
      #- shared-net
networks:
  my-net:
    driver: "bridge"
    name: my-net
  #shared-net:
    #external: true
